name: simple_rich_text
description: Display a Dart string in Flutter using simple rich text characters.
version: 1.0.26        #NOEDIT
homepage: https://github.com/remoteportal/simple_rich_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
